// Implementation file for parser generated by fsyacc
module InputParser
#nowarn "64";; // turn off warnings that type variables used in production annotations are instantiated to concrete type
open FSharp.Text.Lexing
open FSharp.Text.Parsing.ParseHelpers
# 1 "InputParser.fsp"

open Input

# 10 "InputParser.fs"
// This type is the type of tokens accepted by the parser
type token = 
  | ASSIGN
  | LBRAK
  | RBRAK
  | COMMA
  | EOF
  | NUM of (int)
  | VAR of (string)
// This type is used to give symbolic names to token indexes, useful for error messages
type tokenId = 
    | TOKEN_ASSIGN
    | TOKEN_LBRAK
    | TOKEN_RBRAK
    | TOKEN_COMMA
    | TOKEN_EOF
    | TOKEN_NUM
    | TOKEN_VAR
    | TOKEN_end_of_input
    | TOKEN_error
// This type is used to give symbolic names to token indexes, useful for error messages
type nonTerminalId = 
    | NONTERM__startstart
    | NONTERM_start
    | NONTERM_assignment
    | NONTERM_l
    | NONTERM_x
    | NONTERM_a

// This function maps tokens to integer indexes
let tagOfToken (t:token) = 
  match t with
  | ASSIGN  -> 0 
  | LBRAK  -> 1 
  | RBRAK  -> 2 
  | COMMA  -> 3 
  | EOF  -> 4 
  | NUM _ -> 5 
  | VAR _ -> 6 

// This function maps integer indexes to symbolic token ids
let tokenTagToTokenId (tokenIdx:int) = 
  match tokenIdx with
  | 0 -> TOKEN_ASSIGN 
  | 1 -> TOKEN_LBRAK 
  | 2 -> TOKEN_RBRAK 
  | 3 -> TOKEN_COMMA 
  | 4 -> TOKEN_EOF 
  | 5 -> TOKEN_NUM 
  | 6 -> TOKEN_VAR 
  | 9 -> TOKEN_end_of_input
  | 7 -> TOKEN_error
  | _ -> failwith "tokenTagToTokenId: bad token"

/// This function maps production indexes returned in syntax errors to strings representing the non terminal that would be produced by that production
let prodIdxToNonTerminal (prodIdx:int) = 
  match prodIdx with
    | 0 -> NONTERM__startstart 
    | 1 -> NONTERM_start 
    | 2 -> NONTERM_assignment 
    | 3 -> NONTERM_assignment 
    | 4 -> NONTERM_assignment 
    | 5 -> NONTERM_l 
    | 6 -> NONTERM_l 
    | 7 -> NONTERM_x 
    | 8 -> NONTERM_a 
    | _ -> failwith "prodIdxToNonTerminal: bad production index"

let _fsyacc_endOfInputTag = 9 
let _fsyacc_tagOfErrorTerminal = 7

// This function gets the name of a token as a string
let token_to_string (t:token) = 
  match t with 
  | ASSIGN  -> "ASSIGN" 
  | LBRAK  -> "LBRAK" 
  | RBRAK  -> "RBRAK" 
  | COMMA  -> "COMMA" 
  | EOF  -> "EOF" 
  | NUM _ -> "NUM" 
  | VAR _ -> "VAR" 

// This function gets the data carried by a token as an object
let _fsyacc_dataOfToken (t:token) = 
  match t with 
  | ASSIGN  -> (null : System.Object) 
  | LBRAK  -> (null : System.Object) 
  | RBRAK  -> (null : System.Object) 
  | COMMA  -> (null : System.Object) 
  | EOF  -> (null : System.Object) 
  | NUM _fsyacc_x -> Microsoft.FSharp.Core.Operators.box _fsyacc_x 
  | VAR _fsyacc_x -> Microsoft.FSharp.Core.Operators.box _fsyacc_x 
let _fsyacc_gotos = [| 0us; 65535us; 1us; 65535us; 0us; 1us; 2us; 65535us; 0us; 2us; 11us; 10us; 2us; 65535us; 7us; 8us; 13us; 14us; 2us; 65535us; 0us; 4us; 11us; 4us; 3us; 65535us; 5us; 6us; 7us; 12us; 13us; 12us; |]
let _fsyacc_sparseGotoTableRowOffsets = [|0us; 1us; 3us; 6us; 9us; 12us; |]
let _fsyacc_stateToProdIdxsTableElements = [| 1us; 0us; 1us; 0us; 2us; 1us; 4us; 1us; 1us; 2us; 2us; 3us; 2us; 2us; 3us; 1us; 2us; 1us; 3us; 1us; 3us; 1us; 3us; 2us; 4us; 4us; 1us; 4us; 2us; 5us; 6us; 1us; 5us; 1us; 5us; 1us; 7us; 1us; 8us; |]
let _fsyacc_stateToProdIdxsTableRowOffsets = [|0us; 2us; 4us; 7us; 9us; 12us; 15us; 17us; 19us; 21us; 23us; 26us; 28us; 31us; 33us; 35us; 37us; |]
let _fsyacc_action_rows = 17
let _fsyacc_actionTableElements = [|1us; 32768us; 6us; 15us; 0us; 49152us; 2us; 32768us; 3us; 11us; 4us; 3us; 0us; 16385us; 1us; 32768us; 0us; 5us; 2us; 32768us; 1us; 7us; 5us; 16us; 0us; 16386us; 1us; 32768us; 5us; 16us; 1us; 32768us; 2us; 9us; 0us; 16387us; 0us; 16388us; 1us; 32768us; 6us; 15us; 1us; 16390us; 3us; 13us; 1us; 32768us; 5us; 16us; 0us; 16389us; 0us; 16391us; 0us; 16392us; |]
let _fsyacc_actionTableRowOffsets = [|0us; 2us; 3us; 6us; 7us; 9us; 12us; 13us; 15us; 17us; 18us; 19us; 21us; 23us; 25us; 26us; 27us; |]
let _fsyacc_reductionSymbolCounts = [|1us; 2us; 3us; 5us; 3us; 3us; 1us; 1us; 1us; |]
let _fsyacc_productionToNonTerminalTable = [|0us; 1us; 2us; 2us; 2us; 3us; 3us; 4us; 5us; |]
let _fsyacc_immediateActions = [|65535us; 49152us; 65535us; 16385us; 65535us; 65535us; 16386us; 65535us; 65535us; 16387us; 65535us; 65535us; 65535us; 65535us; 16389us; 16391us; 16392us; |]
let _fsyacc_reductions ()  =    [| 
# 114 "InputParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : A)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
                      raise (FSharp.Text.Parsing.Accept(Microsoft.FSharp.Core.Operators.box _1))
                   )
                 : '_startstart));
# 123 "InputParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : A)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 16 "InputParser.fsp"
                                                          _1 
                   )
# 16 "InputParser.fsp"
                 : A));
# 134 "InputParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'x)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : 'a)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 19 "InputParser.fsp"
                                                          VarInit(_1, _3) 
                   )
# 19 "InputParser.fsp"
                 : A));
# 146 "InputParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'x)) in
            let _4 = (let data = parseState.GetInput(4) in (Microsoft.FSharp.Core.Operators.unbox data : 'l)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 20 "InputParser.fsp"
                                                          ArrayInit(_1, _4) 
                   )
# 20 "InputParser.fsp"
                 : A));
# 158 "InputParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : A)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : A)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 21 "InputParser.fsp"
                                                          Sequence(_1, _3) 
                   )
# 21 "InputParser.fsp"
                 : A));
# 170 "InputParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'a)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : 'l)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 24 "InputParser.fsp"
                                                          ArraySequence(_1, _3)
                   )
# 24 "InputParser.fsp"
                 : 'l));
# 182 "InputParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'a)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 25 "InputParser.fsp"
                                                          Num(_1) 
                   )
# 25 "InputParser.fsp"
                 : 'l));
# 193 "InputParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 27 "InputParser.fsp"
                                                          _1 
                   )
# 27 "InputParser.fsp"
                 : 'x));
# 204 "InputParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : int)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 28 "InputParser.fsp"
                                                          _1 
                   )
# 28 "InputParser.fsp"
                 : 'a));
|]
# 216 "InputParser.fs"
let tables () : FSharp.Text.Parsing.Tables<_> = 
  { reductions= _fsyacc_reductions ();
    endOfInputTag = _fsyacc_endOfInputTag;
    tagOfToken = tagOfToken;
    dataOfToken = _fsyacc_dataOfToken; 
    actionTableElements = _fsyacc_actionTableElements;
    actionTableRowOffsets = _fsyacc_actionTableRowOffsets;
    stateToProdIdxsTableElements = _fsyacc_stateToProdIdxsTableElements;
    stateToProdIdxsTableRowOffsets = _fsyacc_stateToProdIdxsTableRowOffsets;
    reductionSymbolCounts = _fsyacc_reductionSymbolCounts;
    immediateActions = _fsyacc_immediateActions;
    gotos = _fsyacc_gotos;
    sparseGotoTableRowOffsets = _fsyacc_sparseGotoTableRowOffsets;
    tagOfErrorTerminal = _fsyacc_tagOfErrorTerminal;
    parseError = (fun (ctxt:FSharp.Text.Parsing.ParseErrorContext<_>) -> 
                              match parse_error_rich with 
                              | Some f -> f ctxt
                              | None -> parse_error ctxt.Message);
    numTerminals = 10;
    productionToNonTerminalTable = _fsyacc_productionToNonTerminalTable  }
let engine lexer lexbuf startState = (tables ()).Interpret(lexer, lexbuf, startState)
let start lexer lexbuf : A =
    Microsoft.FSharp.Core.Operators.unbox ((tables ()).Interpret(lexer, lexbuf, 0))
